# Generated by Django 5.2.8 on 2025-12-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, null=True),
        ),
    ]
