# Generated by Django 5.2.8 on 2026-01-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
