# Generated by Django 5.2.8 on 2025-11-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_counded_view_post_created_date_post_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='counded_view',
            new_name='counted_views',
        ),
    ]
